/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_efurture_encrypt_Encrypt */

#ifndef _Included_org_efurture_encrypt_Encrypt
#define _Included_org_efurture_encrypt_Encrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_efurture_encrypt_Encrypt
 * Method:    doCmd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_efurture_encrypt_Encrypt_doCmd
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
